org.gradle.jvmargs=-Xmx2G
org.gradle.workers.max=1
org.gradle.daemon=false
gtnh.settings.blowdryerTag=0.2.2
modName=AiBot
modId=aibot
modGroup=com.bot.aibot
useModGroupForPublishing=true
autoUpdateBuildScript=false
minecraftVersion=1.7.10
forgeVersion=10.13.4.1614
channel=stable
mappingsVersion=12
remoteMappings=https\://raw.githubusercontent.com/MinecraftForge/FML/1.7.10/conf/
developmentEnvironmentUserName=Developer
enableModernJavaSyntax=false
enableGenericInjection=true
generateGradleTokenClass=com.bot.aibot.Tags
gradleTokenVersion=VERSION
replaceGradleTokenInFile=
apiPackage=
accessTransformersFile=
usesMixins=false
separateMixinSourceSet=
usesMixinDebug=false
mixinPlugin=
mixinsPackage=
coreModClass=
containsMixinsAndOrCoreModOnly=false
forceEnableMixins=false
usesShadowedDependencies=true
minimizeShadowedDependencies=false
relocateShadowedDependencies=true
includeWellKnownRepositories=true
excludeWellKnownRepositories=
usesMavenPublishing=false
modrinthProjectId=
modrinthRelations=
curseForgeProjectId=
curseForgeRelations=
customArchiveBaseName=AiBot-MC1.7.10-GTNH2.8.4
modVersion=1.0.2-gtnh284
